apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: E:\kuberctl\kompose.exe -f docker-compose.prod.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: accessmanager
  name: accessmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: accessmanager
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: E:\kuberctl\kompose.exe -f docker-compose.prod.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: accessmanager
    spec:
      containers:
        - env:
            - name: AZURE_BLOB_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  key: AZURE_BLOB_SERVICE_URL
                  name: accessmanager-prod-env
            - name: AZURE_CONTAINER_NAME
              valueFrom:
                configMapKeyRef:
                  key: AZURE_CONTAINER_NAME
                  name: accessmanager-prod-env
            - name: FLASK_ENV
              value: production
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                configMapKeyRef:
                  key: SLACK_WEBHOOK_URL
                  name: accessmanager-prod-env
            - name: USE_AZURE_STORAGE
              valueFrom:
                configMapKeyRef:
                  key: USE_AZURE_STORAGE
                  name: accessmanager-prod-env
          image: accessmanager
          name: accessmanager
          volumeMounts:
            - mountPath: /usr/src/app
              name: accessmanager-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: accessmanager-cm0
          name: accessmanager-cm0
