apiVersion: v1
data:
  AZURE_KEY_DEV: 5Gh95l8YoDX3RYg09L4ddtMlqdB4FiytyiYe7or6UgyuT5dHZROEJQQJ99AGACi5YpzOiMkAAAAgAZMPV9Mx
  AZURE_KEY_MUNICH: 7Jb4QKGoOD61ImHvvWcjFYa7PZQlgljRbwaYXsq4wXn0FJJcbDBKJQQJ99AGACi5YpzOiMkAAAAgAZMP8T14
  AZURE_KEY_STOCKHOLM: 5c5huzghrC2cqEK4CRWbQ5qbC23v4wgchGrDQ151QSrA7dNCAG4jJQQJ99AGACi5YpzOiMkAAAAgAZMPHnK9
  PATH_TO_IMAGE_TILES: /usr/src/app/downloads/pulse_tiles
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: api-api-env
  name: api-env
