trigger:
  branches:
    include:
      - master  

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'parkpulse-azure-subscription'
  azureContainerRegistry: 'parkpulsedocker'
  dockerComposeFile: 'docker-compose.yml'
  imageTag: 'v1.0.0'
  DOCKER_USERNAME: $(DOCKER_USERNAME)
  DOCKER_PASSWORD: $(DOCKER_PASSWORD)

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - checkout: self

          - task: DownloadSecureFile@1
            name: sshPrivateKey
            displayName: 'Download SSH private key'
            inputs:
              secureFile: 'id_rsa'

          - script: |
              set -x  # Print commands as they are executed
              set -e  # Exit on error

              echo Installing SSH key $(sshPrivateKey.secureFilePath)...
              
              # Create .ssh directory
              mkdir -p ~/.ssh
              
              # Move the SSH key to the .ssh directory
              mv $(sshPrivateKey.secureFilePath) ~/.ssh/id_rsa
              
              # Set the appropriate permissions
              chmod 600 ~/.ssh/id_rsa
              
              # Start the SSH agent and add the key
              eval "$(ssh-agent -s)"
              ssh-add ~/.ssh/id_rsa
              
              # Configure Git to use the SSH key
              git config --global core.sshCommand "ssh -i ~/.ssh/id_rsa -F /dev/null"

              ssh -T git@github.com || true
            displayName: 'Setting Github SSH Key'

          - script: |
              head -n 3 ~/.ssh/id_rsa
              trail -n 3 ~/.ssh/id_rsa
              chmod +x ./init_project.sh 
              ./init_project.sh
            displayName: 'Initialize Project'

          - script: |
              set -x 
              docker compose -f $(dockerComposeFile) build
            displayName: 'Build Docker Images'

          - script: |
              echo $(DOCKER_PASSWORD) | docker login $(azureContainerRegistry).azurecr.io -u $(DOCKER_USERNAME) --password-stdin
            displayName: 'Login to Azure Container Registry'

          - script: |
              docker compose -f $(dockerComposeFile) push
            displayName: 'Push Docker Images'

  - stage: Deploy
    dependsOn: Build
    jobs:
      - job: Deploy
        steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: $(azureSubscription)
              appName: 'server-container'
              images: |
                $(azureContainerRegistry).azurecr.io/parkpulse-accessmanager:$(imageTag)
                $(azureContainerRegistry).azurecr.io/parkpulse-api:$(imageTag)
                $(azureContainerRegistry).azurecr.io/parkpulse-web:$(imageTag)
                $(azureContainerRegistry).azurecr.io/nginx:$(imageTag)