trigger:
  branches:
    include:
      - master  

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'parkpulse-azure-subscription'
  azureContainerRegistry: 'parkpulsedocker'
  dockerComposeFile: 'docker-compose.prod.yml'
  imageTag: 'v1.0.1'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - checkout: self
            persistCredentials: true

          - script: |
              git config --global url."https://$(GITHUB_PAT)@github.com/".insteadOf "https://github.com/"
              git submodule update --init --recursive
            displayName: 'Initialize submodules'

          - task: DownloadSecureFile@1
            displayName: 'Download secure files'
            inputs:
              secureFile: .web.env

          - task: DownloadSecureFile@1
            displayName: 'Download secure files'
            inputs:
              secureFile: .accessmanager.prod.env

          - task: CopyFiles@2
            displayName: 'Copy Files to: $(System.DefaultWorkingDirectory)'
            inputs:
              SourceFolder: '$(Agent.TempDirectory)'
              Contents: .web.env
              TargetFolder: '$(System.DefaultWorkingDirectory)'

          - task: CopyFiles@2
            displayName: 'Copy Files to: $(System.DefaultWorkingDirectory)'
            inputs:
              SourceFolder: '$(Agent.TempDirectory)'
              Contents: .accessmanager.prod.env
              TargetFolder: '$(System.DefaultWorkingDirectory)'

          - script: |
              set -x 
              mkdir parkpulse-web/downloads
              docker compose -f $(dockerComposeFile) -p parkpulse build 
            displayName: 'Build Docker Images'

          - script: |
              docker tag parkpulse-accessmanager:latest $(azureContainerRegistry).azurecr.io/parkpulse-accessmanager:$(imageTag) 
              docker tag parkpulse-web:latest $(azureContainerRegistry).azurecr.io/parkpulse-web:$(imageTag) 
            displayName: 'Tag Docker Images'

          - script: |
              echo $(DOCKER_PASSWORD) | docker login $(azureContainerRegistry).azurecr.io -u $(DOCKER_USERNAME) --password-stdin
            displayName: 'Login to Azure Container Registry'
          
          - script: |
              docker images
            displayName: 'Listing images'

          - script: |
              docker push $(azureContainerRegistry).azurecr.io/parkpulse-accessmanager:$(imageTag)
              docker push $(azureContainerRegistry).azurecr.io/parkpulse-web:$(imageTag)
            displayName: 'Push Docker Images to Azure Container Registry'



  - stage: Deploy
    dependsOn: Build
    jobs:
      - job: DeployAccessManager
        steps:
          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: $(azureSubscription)
              appName: parkpulse-accessmanager
              imageName: $(azureContainerRegistry).azurecr.io/parkpulse-accessmanager:$(imageTag) 

      - job: DeployWeb
        steps:
          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: $(azureSubscription)
              appName: parkpulse-web
              imageName: $(azureContainerRegistry).azurecr.io/parkpulse-web:$(imageTag) 
