trigger:
  branches:
    include:
      - master  

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'parkpulse-azure-subscription'
  azureContainerRegistry: 'parkpulsedocker'
  dockerComposeFile: 'docker-compose.yml'
  imageTag: 'v1.0.0'
  appName: 'ParkPulse-Web'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - checkout: self
            persistCredentials: true

          - script: |
              git config --global url."https://$(GITHUB_PAT)@github.com/".insteadOf "https://github.com/"
              git submodule update --init --recursive
            displayName: 'Initialize submodules'

          - task: DownloadSecureFile@1
            displayName: 'Download secure files'
            inputs:
              secureFile: .api.env

          - task: DownloadSecureFile@1
            displayName: 'Download secure files'
            inputs:
              secureFile: .accessmanager.prod.env

          - task: CopyFiles@2
            displayName: 'Copy Files to: $(System.DefaultWorkingDirectory)'
            inputs:
              SourceFolder: '$(Agent.TempDirectory)'
              Contents: .api.env
              TargetFolder: '$(System.DefaultWorkingDirectory)'

          - task: CopyFiles@2
            displayName: 'Copy Files to: $(System.DefaultWorkingDirectory)'
            inputs:
              SourceFolder: '$(Agent.TempDirectory)'
              Contents: .accessmanager.prod.env
              TargetFolder: '$(System.DefaultWorkingDirectory)'


          - script: |
              set -x 
              mkdir parkpulse-api/downloads
              docker compose -f $(dockerComposeFile) build
            displayName: 'Build Docker Images'

          - script: |
              echo $(DOCKER_PASSWORD) | docker login $(azureContainerRegistry).azurecr.io -u $(DOCKER_USERNAME) --password-stdin
            displayName: 'Login to Azure Container Registry'

          - script: |
              docker compose -f $(dockerComposeFile) push
            displayName: 'Push Docker Images'

  - stage: Deploy
    dependsOn: Build
    jobs:
      - job: Deploy
        steps:
          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: $(azureSubscription)
              appName: $(appName)
              multicontainerConfigFile: $(dockerComposeFile)
              images: |
                $(azureContainerRegistry).azurecr.io/parkpulse-accessmanager:$(imageTag)
                $(azureContainerRegistry).azurecr.io/parkpulse-api:$(imageTag)
                $(azureContainerRegistry).azurecr.io/parkpulse-web:$(imageTag)
                $(azureContainerRegistry).azurecr.io/nginx:$(imageTag)