networks:
  internal_net:
  frontend_net:

services:
  web:
    build:
      context: ./parkpulse-web
      dockerfile: Dockerfile.dev
    volumes:
      - downloads:/usr/src/app/downloads
    env_file:
      - .web.env
    environment:
      - FLASK_ENV=development
    ports:
      - 5000:5000
    networks:
      - internal_net
      - frontend_net

  accessmanager:
    build:
      context: ./parkpulse-accessmanager
      dockerfile: Dockerfile.dev
    env_file:
      - .accessmanager.dev.env
    environment:
      - FLASK_ENV=development
    ports:
      - 5002:5000
    depends_on: # to seperate logs
      - web
    networks:
      - internal_net
      - frontend_net
volumes:
  downloads: