networks:
  internal_net:
  frontend_net:

services:
  web:
    build:
      context: ./parkpulse-web
      dockerfile: Dockerfile.dev
    volumes:
      - downloads:/usr/src/app/downloads
      - ./parkpulse-web:/usr/src/app #can cause issues but enables live reload
    env_file:
      - .web.dev.env
    environment:
      - FLASK_ENV=development
    ports:
      - 5000:5000
    networks:
      - internal_net
      - frontend_net

  accessmanager:
    build:
      context: ./parkpulse-accessmanager
      dockerfile: Dockerfile.dev
    volumes:
      - ./parkpulse-accessmanager:/usr/src/app #can cause issues but enables live reload
    env_file:
      - .accessmanager.dev.env
    environment:
      - FLASK_ENV=development
    ports:
      - 5002:5000
    
    networks:
      - internal_net
      - frontend_net
volumes:
  downloads: