networks:
  internal_net:
  frontend_net:

services:
  web:
    build:
      context: ./parkpulse-web/
      dockerfile: Dockerfile
    volumes:
      - ./parkpulse-web:/usr/src/app #can cause issues but enables live reload
    env_file:
      - .web.dev.env
    environment:
      - FLASK_ENV=development
    ports:
      - 8080:8080
    networks: 
      - internal_net
      - frontend_net

  brf:
    build:
      context: ./brf-engine
      dockerfile: Dockerfile

    env_file:
      - .brf.env
    environment:
      - FLASK_ENV=development
    ports:
      - 5001:5000
    networks:
      - internal_net
      - frontend_net


  accessmanager:
    build:
      context: ./parkpulse-accessmanager
      dockerfile: Dockerfile.dev
    volumes:
      - ./parkpulse-accessmanager:/usr/src/app #can cause issues but enables live reload
    env_file:
      - .accessmanager.dev.env
    environment:
      - FLASK_ENV=development
    ports:
      - 5000:5000
    
    networks:
      - internal_net
      - frontend_net
volumes:
  downloads: