networks:
  internal_net:
  frontend_net:

services:
  web:
    build:
      context: ./parkpulse-web
      dockerfile: Dockerfile.dev
    volumes:
      - ./parkpulse-web:/usr/src/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - api
      - accessmanager
    networks:
      - internal_net

  api:
    build:
      context: ./parkpulse-api
      dockerfile: Dockerfile.dev
    volumes:
      - ./parkpulse-api:/usr/src/app
      - downloads:/usr/src/app/downloads
    env_file:
      - .api.env
    environment:
      - FLASK_ENV=development
    depends_on:
      - accessmanager
    networks:
      - internal_net

  accessmanager:
    build:
      context: ./parkpulse-accessmanager
      dockerfile: Dockerfile.dev
    volumes:
      - ./parkpulse-accessmanager:/usr/src/app
    ports:
      - "5002:5000"
    env_file:
      - .accessmanager.dev.env
    environment:
      - FLASK_ENV=development
    networks:
      - internal_net

  nginx:
    image: nginx:latest
    ports:
      - "443:443" # HTTPS
      - "80:80"   # HTTP
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - frontend_net
      - internal_net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - internal_net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=yourpassword
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - frontend_net
      - internal_net


volumes:
  downloads:
  grafana-storage: