apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: downloads
  name: downloads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
