apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: E:\kuberctl\kompose.exe -f docker-compose.prod.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: E:\kuberctl\kompose.exe -f docker-compose.prod.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: web
    spec:
      containers:
        - env:
            - name: FLASK_ENV
              value: production
          image: web
          name: web
          volumeMounts:
            - mountPath: /usr/src/app
              name: web-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: web-cm0
          name: web-cm0
